DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS post_reaction;
DROP TABLE IF EXISTS comment_reaction;